### ISSUE TITLE
Edge clicker color

### ISSUE THREAD

**Issue by cesards** [romannurik/portfolio#2]
Hi @romannurik ! Really nice job! I've been having a look to your code because I wanted to get the same pages effect in my site. I realised that the edge image is encripted. Could you place share how did you get the effect in order to give me the opportunity to create another svg for my site?

``` css
background-image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNiIgaGVpZ2h0PSIxM...);
background-position: 0% 0%;
```

Thank you so much. If I find any issue on the porfolio related to any browser or content size I'll let you know :+1: (and If Im working on that, I have no problems in make a PR)

**Comment by romannurik** [comment]
Hey there! It's just base64 encoded; pretty easy to decode. Here are the decoded versions of previous and next:

**previous_edge.svg**

```
<svg width="6" height="12" viewBox="0 0 6 12" xmlns="http://www.w3.org/2000/svg">
  <path d="M0 0l6 6-6 6" fill="#FFF" fill-rule="evenodd"/>
</svg>
```

**next_edge.svg**

```
<svg width="6" height="12" viewBox="0 0 6 12" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 0L0 6l6 6" fill="#FFF" fill-rule="evenodd"/>
</svg>
```

**Comment by cesards** [comment]
Lot of thanks! :beers:
